language: ruby

rvm:
  - 2.3.3
  - 2.2
  - 2.1

# to avoid travis-ci issue since 2015-12-25
before_install:
  - gem update bundler

gemfile:
  - Gemfile
  - gemfiles/fluentd_v0.12.gemfile
  - gemfiles/fluentd_v0.14.gemfile

matrix:
  include:
    - rvm: 1.9.3
      gemfile: gemfiles/fluentd_v0.10.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/fluentd_v0.10.gemfile
  allow_failures:
    gemfile: gemfiles/fluentd_v0.10.gemfile
